// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3PYCjj7PS5rk5C6TzmDB_hIEoyq0mzF8',
    appId: '1:111804340355:web:299a81711749451985a3b6',
    messagingSenderId: '111804340355',
    projectId: 'moval-a8153',
    authDomain: 'moval-a8153.firebaseapp.com',
    storageBucket: 'moval-a8153.firebasestorage.app',
    measurementId: 'G-LCXR5XRWGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABIs6QvaTAAFiOH-iZqGlGZQ4v_CH4e94',
    appId: '1:111804340355:android:5c81de991a4fad2885a3b6',
    messagingSenderId: '111804340355',
    projectId: 'moval-a8153',
    storageBucket: 'moval-a8153.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl076apXlP8CPbGR039QDMCzkEFYNCMwQ',
    appId: '1:111804340355:ios:e03d3827c2a7c80985a3b6',
    messagingSenderId: '111804340355',
    projectId: 'moval-a8153',
    storageBucket: 'moval-a8153.firebasestorage.app',
    iosBundleId: 'com.example.moval',
  );
}
